"""Adicionando coluna ficha_tecnica_id

Revision ID: 102cae994de6
Revises: 9238390d1cd6
Create Date: 2024-10-16 15:59:26.255232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102cae994de6'
down_revision = '9238390d1cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ficha_tecnica_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ficha_tecnica', ['ficha_tecnica_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ficha_tecnica_id')

    # ### end Alembic commands ###
