"""Criando tabela de estoque

Revision ID: c3fd8e9b863b
Revises: 
Create Date: 2024-10-10 10:32:28.143547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3fd8e9b863b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_tecido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_tela', sa.String(length=100), nullable=False),
    sa.Column('quantidade_tela', sa.Integer(), nullable=False),
    sa.Column('tipo_tela', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Ordem_Producao')
    op.drop_table('Entrega')
    op.drop_table('Estoque_tecido')
    op.drop_constraint('Produto_fk6', 'Produto', type_='foreignkey')
    op.drop_table('Fornecedore')
    op.drop_table('Produto')
    op.drop_table('Cliente')
    op.drop_table('Entregador')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('Entregador',
    sa.Column('Id_Entregador', sa.INTEGER(), server_default=sa.text('nextval(\'"Entregador_Id_Entregador_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Nome_Entregador', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Cnpj_Entregador', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id_Entregador', name='Entregador_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Cliente',
    sa.Column('Id_Cliente', sa.INTEGER(), server_default=sa.text('nextval(\'"Cliente_Id_Cliente_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Nome_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'100'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Endereco_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'255'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Telefone_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'20'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Email_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'100'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Cnpj_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'14'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Cidade_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'100'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Estado_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'2'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Cep_Cliente', sa.VARCHAR(length=255), server_default=sa.text("'10'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id_Cliente', name='Cliente_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Produto',
    sa.Column('Id_Produto', sa.INTEGER(), server_default=sa.text('nextval(\'"Produto_Id_Produto_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Nome_Produto', sa.VARCHAR(length=255), server_default=sa.text("'100'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Preco_Produto', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('Qt_Estoque', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Categoria_Produto', sa.VARCHAR(length=255), server_default=sa.text("'50'::character varying"), autoincrement=False, nullable=True),
    sa.Column('Peso_Produto', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('Id_Fornecedor', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Unidade_Medida', sa.VARCHAR(length=255), server_default=sa.text("'10'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_Fornecedor'], ['Fornecedore.Id_Fornecedor'], name='Produto_fk6'),
    sa.PrimaryKeyConstraint('Id_Produto', name='Produto_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Fornecedore',
    sa.Column('Id_Fornecedor', sa.INTEGER(), server_default=sa.text('nextval(\'"Fornecedore_Id_Fornecedor_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Nome_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'100'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Endereco_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'255'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Telefone_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'20'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Email_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'100'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Cnpj_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'14'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Tipo_fornecedor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Cidade_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'100'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Estado_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'2'::character varying"), autoincrement=False, nullable=False),
    sa.Column('Cep_Fornecedor', sa.VARCHAR(length=255), server_default=sa.text("'10'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id_Fornecedor', name='Fornecedore_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Estoque_tecido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_tela', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantidade_tela', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_tela', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unidade_medida', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Estoque_tecido_pkey')
    )
    op.create_table('Entrega',
    sa.Column('Id_Cliente', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Nome_Cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Endereco_Cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Telefone_Cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Cidade_Cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Estado_Cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Cep_Cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Id_Entregador', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Nome_Entregador', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Data_Entrega', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Qt_Pedido', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Id_Cliente'], ['Cliente.Id_Cliente'], name='Entrega_fk0'),
    sa.ForeignKeyConstraint(['Id_Entregador'], ['Entregador.Id_Entregador'], name='Entrega_fk7')
    )
    op.create_table('Ordem_Producao',
    sa.Column('Ordem_Prioridade', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Id_Ordem', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Id_Produto', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Nome_Produto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Qt_Pedido', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Data_Inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Data_Fim', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Status_Ordem', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Id_Usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Obs_Ordem', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Data_Cadastro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('Custo_Estimado', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('Custo_Real', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('Data_Entrega', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Id_Cliente', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Nome_Cliente', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Endereco_Entrega', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Lista_Materiais', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Qt_Materiais', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Qt_Pronto', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Id_Cliente'], ['Cliente.Id_Cliente'], name='Ordem_Producao_fk14'),
    sa.ForeignKeyConstraint(['Id_Produto'], ['Produto.Id_Produto'], name='Ordem_Producao_fk2'),
    sa.PrimaryKeyConstraint('Id_Ordem', name='Ordem_Producao_pkey')
    )
    op.drop_table('estoque_tecido')
    # ### end Alembic commands ###
