"""Alterando Quantidade de alça de INT pra FLoat

Revision ID: f0ba3c3b732c
Revises: ce98a7c91dbc
Create Date: 2024-10-17 10:02:02.755074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ba3c3b732c'
down_revision = 'ce98a7c91dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_alca', schema=None) as batch_op:
        batch_op.alter_column('quantidade_alca',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_alca', schema=None) as batch_op:
        batch_op.alter_column('quantidade_alca',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
