"""Alterando Modelo de classes DB

Revision ID: fb1fb55aeafb
Revises: 9525374451b3
Create Date: 2024-10-17 13:21:03.748828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1fb55aeafb'
down_revision = '9525374451b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ficha_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('pedido_cliente_ficha_tecnica_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ficha_tecnica', ['ficha_id'], ['id'])
        batch_op.drop_column('ficha_tecnica_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ficha_tecnica_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pedido_cliente_ficha_tecnica_id_fkey', 'ficha_tecnica', ['ficha_tecnica_id'], ['id'])
        batch_op.drop_column('ficha_id')

    # ### end Alembic commands ###
