"""create pedido_cliente table

Revision ID: 164b1d1fa206
Revises: a1e4c8f9f601
Create Date: 2024-10-11 16:16:33.013391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164b1d1fa206'
down_revision = 'a1e4c8f9f601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=255), nullable=False),
    sa.Column('produto', sa.String(length=255), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_entrega', sa.DateTime(), nullable=False),
    sa.Column('entregador', sa.String(length=100), nullable=False),
    sa.Column('emissor_pedido', sa.String(length=100), nullable=False),
    sa.Column('tamanho', sa.String(length=50), nullable=False),
    sa.Column('tela', sa.String(length=100), nullable=False),
    sa.Column('alca', sa.String(length=100), nullable=False),
    sa.Column('estampa', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade_volumes', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pedidos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_cliente', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('produto', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data_emissao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_entrega', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('entregador', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('emissor_pedido', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tamanho', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tela', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('alca', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estampa', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qtd_volumes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pedidos_pkey')
    )
    op.drop_table('pedido_cliente')
    # ### end Alembic commands ###
