"""Adicionando o campo gramatura no estoque de tecidos

Revision ID: 1b0e67ae1607
Revises: fb1fb55aeafb
Create Date: 2024-10-18 14:03:17.079867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0e67ae1607'
down_revision = 'fb1fb55aeafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_tecido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gramatura', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_tecido', schema=None) as batch_op:
        batch_op.drop_column('gramatura')

    # ### end Alembic commands ###
