"""Adicionando campo medida_alca ao PedidoCliente

Revision ID: 3c4308871ea1
Revises: 164b1d1fa206
Create Date: 2024-10-14 11:53:16.437447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4308871ea1'
down_revision = '164b1d1fa206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medida_alca', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.drop_column('medida_alca')

    # ### end Alembic commands ###
