"""Alterando o sistema de autenticação para Flask-Login

Revision ID: 920c3ea4964c
Revises: 951bc4937037
Create Date: 2024-10-21 15:16:58.910052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920c3ea4964c'
down_revision = '951bc4937037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operador', sa.String(length=100), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint(None, ['usuario'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.drop_column('operador')

    # ### end Alembic commands ###
