"""Adicionando modelo de Ficha Técnica

Revision ID: 9238390d1cd6
Revises: a336a21172a8
Create Date: 2024-10-15 14:45:05.588085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9238390d1cd6'
down_revision = 'a336a21172a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('insumos', sa.Text(), nullable=False),
    sa.Column('custo_producao', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ficha_tecnica')
    # ### end Alembic commands ###
