"""Criar tabela Estoque_alca

Revision ID: a1e4c8f9f601
Revises: c3fd8e9b863b
Create Date: 2024-10-10 16:29:33.759690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e4c8f9f601'
down_revision = 'c3fd8e9b863b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_alca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_alca', sa.String(length=255), nullable=False),
    sa.Column('quantidade_alca', sa.Integer(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Estoque_alca')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('Estoque_alca',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_alca', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantidade_alca', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('unidade_medida', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Estoque_alca_pkey')
    )
    op.drop_table('estoque_alca')
    # ### end Alembic commands ###
