"""Alterando modelo de dados do cadastro de pedidos

Revision ID: ce98a7c91dbc
Revises: fd08f7b243a1
Create Date: 2024-10-17 09:31:04.727665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce98a7c91dbc'
down_revision = 'fd08f7b243a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_tecido', schema=None) as batch_op:
        batch_op.alter_column('quantidade_tela',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_tecido', schema=None) as batch_op:
        batch_op.alter_column('quantidade_tela',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
