"""Modificando modelo de dados PedidoCliente

Revision ID: f255371138ba
Revises: 920c3ea4964c
Create Date: 2025-01-20 11:32:31.479514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f255371138ba'
down_revision = '920c3ea4964c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rota', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_cliente', schema=None) as batch_op:
        batch_op.drop_column('rota')

    # ### end Alembic commands ###
